### PR TITLE
Updates SQL prepared statements containing ambiguous GROUP BY clauses

### PR DESCRIPTION
**Pull request by justaFluffypanda**
See comment on commit

### CODE REVIEW

**Comment by 13ace37** [comment]
> As you can see the query does return a list of names, and while it pulls the correct times the names and steamids associated with those times are incorrect.

```SQL
SELECT MIN(runtimepro), name, steamid, style FROM surftimer.ck_playertimes WHERE mapname = 'surf_rookie' AND runtimepro > -1.0 GROUP BY style;
```

MIN(runtimepro) | name | steamid | style
-- | -- | -- | --
146.748 | Zackboom | STEAM_1:0:71688943 | 0
177.305 | ๑ﭥ Ace ֎ | STEAM_1:0:137835683 | 2
214.59 | ๑ﭥ  Flupsi | STEAM_1:0:76620969 | 4

```SQL
SELECT * FROM surftimer.ck_playertimes WHERE mapname = "surf_rookie" AND style = 0 LIMIT 1;
```

steamid | mapname | name | runtimepro | style
-- | -- | -- | -- | --
STEAM_1:0:71688943 | surf_rookie | Zackboom | 146.748 | 0

```SQL
SELECT * FROM surftimer.ck_playertimes WHERE mapname = "surf_rookie" AND style = 2 LIMIT 1;
```

steamid | mapname | name | runtimepro | style
-- | -- | -- | -- | --
STEAM_1:0:137835683 | surf_rookie | ๑ﭥ Ace ֎ | 177.305 | 2


```SQL
SELECT * FROM surftimer.ck_playertimes WHERE mapname = "surf_rookie" AND style = 4 LIMIT 1;
```

steamid | mapname | name | runtimepro | style
-- | -- | -- | -- | --
STEAM_1:0:76620969 | surf_rookie | ๑ﭥ  Flupsi | 214.59 | 4

---

And I don't know if MySQL is still a good choice in 2019. I had no good experience while using MySQL back in the days. As you can see above its working fine with MariaDB 10.3.18.

**Comment by justaFluffypanda** [comment]
Well if nothing else perhaps someone else running MySQL with their installation can stumble across this thread for help.  I need to update to MariaDB but I hate fixing things that are currently working...

**Comment by 13ace37** [comment]
> but I hate fixing things that are currently working...

But why do you want to change it then ^^

**Comment by justaFluffypanda** [comment]
The current queries appear to be broken for servers running MySQL 5.7+ and it's not really out of the realm of possibility to assume that people are running MySQL since the plugin requirements don't give a suggestion as to a preferred database installation/version.

**Pull request closed without merging**
